apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: peerprep
spec:
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
      - name: history
        image: seanpzk/history-service:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: peerprep
spec:
  type: ClusterIP  # To expose externally
  selector:
    app: history
  ports:
    - protocol: TCP
      port: 9090  # External port
      targetPort: 9090  # Pod's container port

  
