apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionbank
  namespace: peerprep
spec:
  selector:
    matchLabels:
      app: questionbank
  template:
    metadata:
      labels:
        app: questionbank
    spec:
      containers:
        - name: questionbank
          image: seanpzk/questionbank:1.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: questionbank-service
  namespace: peerprep
spec:
  type: ClusterIP # To expose externally
  selector:
    app: questionbank
  ports:
    - protocol: TCP
      port: 8080 # External port
      targetPort: 8080 # Pod's container port

