name: Simple Test Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run a very long script that intentionally exceeds the maximum line width for this yaml file to demonstrate breaking prettier rules
              run: echo "Hello, this is a broken YAML file!"
