name: Lint

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-linter
        id: linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSX: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_YAML: true
          FIX_JAVASCRIPT_ES: true
          FIX_JSX: true
          FIX_TSX: true
          FIX_TYPESCRIPT_ES: true
      
      - name: Commit and push linting fixes
        if: steps.linter.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: dev
          commit_message: "chore: fix linting issues"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}